package com.apuestatotal.app.domain.entity

data class BetHistoryDetailEntity(
    val selectionId: Long,
    val selectionStatus: Int,
    val price: String,
    val name: String,
    val spec: String,
    val marketTypeId: Int,
    val marketId: Long,
    val marketName: String,
    val isLive: Boolean,
    val isBetBuilder: Boolean,
    val isBanker: Boolean,
    val isVirtual: Boolean,
    val bbSelections: Any?,
    val eventId: Long,
    val eventCode: String?,
    val feedEventId: Long,
    val eventName: String,
    val sportTypeId: Int,
    val categoryId: Int,
    val categoryName: String?,
    val champId: Int,
    val champName: String?,
    val eventScore: String?,
    val gameTime: String?,
    val eventDate: String,
    val pitcherInfo: String?,
    val runners: String?,
    val extraEventInfo: String?,
    val rc: Boolean,
    val liveInfoAtEventMinute: String?,
    val isLiveOrVirtual: Boolean,
    val earlyPayout: Boolean,
    val boreDraw: Boolean,
    val deadHeatFactor: String?,
    val dbId: Int
)

